# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Tests
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        env:
          GO111MODULE: on
          GOFLAGS: -mod=vendor
        run: |
          go mod tidy
          go mod vendor
      - name: Build
        env:
          GO111MODULE: on
          GOFLAGS: -mod=vendor
        run: |
          make build
  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      zookeeper:
        image: zookeeper
        ports:
          - 2181:2181
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '0.13.7'
          - '0.14.11'
          - '0.15.5'
          - '1.0.11'
          - '1.1.7'
    steps:
      - name: Install ubuntu dependencies
        run: apt update && apt install -y ca-certificates make gcc

      - name: Set up Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: TF tests
        env:
          GO111MODULE: on
          GOFLAGS: -mod=vendor
        run: |
          go mod tidy
          go mod vendor
          make test

      - name: TF acceptance tests
        timeout-minutes: 10
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
          ZOOKEEPER_HOST: zookeeper
          ZOOKEEPER_PORT: 2181
        run: |
          go mod tidy
          go mod vendor
          make testacc
      - name: Go VET
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
        run: |
          go mod tidy
          go mod vendor
          make vet
